#!/usr/bin/env bash
# installs and configures nginx web server to listen to port 80 and
# serves a page with content `Holberton School` when / is querried

apt-get -y install nginx
mkdir -p /data/www
echo "Holberton School for the win!" > index.html
cp index.html /data/www/
cat > default <<EOF
    server {
        listen 80 default_server;
        root /data/www;
        location / {
            index index.html index.html;
        }
    }
EOF
cp default /etc/nginx/sites-available/default
sudo service nginx restart
