#!/usr/bin/env bash
# installs and configures nginx web server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
service nginx start
