#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page

new_location='\n\t location /redirect_me {\n\t\t rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; \n\t}'
sed -i "/server_name _;/ a\ $new_location" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart
