#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page that 
# contains the string `Ceci n'est pas une page`

apt-get -y update
apt-get -y install nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html
error_line='\n\t error_page 404 /404.html; \n'
sed -i "/server_name _;/ a \ $error_line" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx restart
