#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configures Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
