#!/usr/bin/env bash
#  task #1 fix short and sweet.

sed -i 's/\(listen \(\[::]:\)\?\)80/\18080/g' /etc/nginx/sites-enabled/default
chmod 0644 /etc/nginx/nginx.conf
chmod -R nginx:nginx /etc/nginx
sudo -u nginx service nginx restart
